import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import CreativeConceptBuilder from '@/components/CreativeConceptBuilder';
import ArtzyWorldBriefResume from '@/components/ArtzyWorldBriefResume';

export const metadata: Metadata = { title: "Personalised Art & Gifts | Artzy's Studio", description: "Caricatures, digital art, custom paintings and occasion gifts created personally at Artzy's Studio in Pune.", alternates: { canonical: '/personalised/' } };

const paths = [
  { title: 'Caricatures from photos', copy: 'Turn people, memories and joyful details into expressive digital caricatures.', href: '/caricatures', mark: '01' },
  { title: 'Digital art & canvas prints', copy: 'Commission abstract, modern or story-led artwork made for your wall and space.', href: '/digital-prints', mark: '02' },
  { title: 'Custom name plates', copy: 'Build a hand-painted welcome around your name, entrance and preferred Artzy direction.', href: '/name-plates', mark: '03' },
  { title: 'Occasion & milestone gifts', copy: 'Wedding, anniversary, birthday, housewarming and festive gifts with meaning.', href: '/gifts', mark: '04' },
  { title: 'Custom hand-painted artwork', copy: 'Begin with an object, idea or brief and shape a one-of-a-kind studio creation.', href: '/contact?interest=custom-artwork', mark: '05' },
];

export default function PersonalisedPage() {
  return <><Header/><main className="journey-page">
    <section className="story-hero story-hero--personalised"><img className="story-hero__image" src="/images/personalised-hero-v2.webp" alt="A family photograph becoming a hand-drawn portrait and a finished personalised Artzy-style keepsake"/><div className="story-hero__shade" aria-hidden="true"/><div className="story-hero__copy"><span>Personal · considered · created for you</span><h1>Your story,<br/><em>made visible.</em></h1><p>Choose the kind of piece you have in mind. Deepti and the studio team will help turn your photograph, occasion, space or idea into art that feels unmistakably yours.</p><div className="story-hero__actions"><a className="story-hero__primary" href="#personalised-paths">Find your creative path</a><Link className="story-hero__secondary" href="/contact?interest=personalised">Share your idea</Link></div><small>Artzy-style illustration · Every custom order is confirmed by the studio</small></div></section>
    <div className="story-hero-strip story-hero-strip--four" aria-label="How personalised orders work"><span><b>01</b>Tell us your story</span><span><b>02</b>Review the direction</span><span><b>03</b>Approve before making</span><span><b>04</b>Receive it with care</span></div>
    <section id="personalised-paths" className="journey-paths journey-paths--five"><header><span>CHOOSE YOUR PATH</span><h2>What would you like us to create?</h2></header><div>{paths.map(path=><article id={path.mark === '05' ? 'custom-artwork' : undefined} key={path.title}><small>{path.mark}</small><h3>{path.title}</h3><p>{path.copy}</p><Link href={path.href}>Explore this path <span>→</span></Link></article>)}</div></section>
    <ArtzyWorldBriefResume />
    <CreativeConceptBuilder kind="personalised"/>
    <section className="journey-cta"><span>NOT SURE WHERE TO BEGIN?</span><h2>Start with the story.<br/>We will help with the rest.</h2><Link href="/contact?interest=personalised">Discuss your idea</Link><a href="https://wa.me/919158680722">Ask on WhatsApp</a></section>
  </main><Footer/><style>{`body{background:#fbf6ef}.journey-page{color:#40322b}.journey-hero{min-height:620px;display:grid;grid-template-columns:1.08fr .92fr;background:#f4e9dd}.journey-hero>div{padding:clamp(70px,9vw,135px) clamp(28px,7vw,115px)}.journey-hero span,.journey-paths header span,.journey-cta>span{color:#ad4f54;font-size:.66rem;font-weight:700;letter-spacing:.18em}.journey-hero h1{margin:24px 0;font:400 clamp(4.2rem,8vw,8rem)/.87 var(--font-serif),Georgia,serif;letter-spacing:-.055em}.journey-hero h1 em{color:#ad4f54;font-weight:400}.journey-hero p{max-width:630px;color:#725f55;line-height:1.75}.journey-hero>div>a{display:inline-block;margin-top:26px;padding-bottom:5px;border-bottom:1px solid #ad4f54;color:#9d4449;font-size:.8rem;text-decoration:none}.journey-hero aside{display:grid;align-content:center;padding:70px clamp(28px,6vw,92px);background:#76463f;color:#fff8f1}.journey-hero aside small{color:#efc8bd;font-size:.64rem;letter-spacing:.16em}.journey-hero ol{padding:0;margin:28px 0 0;list-style:none}.journey-hero li{display:flex;align-items:center;gap:22px;padding:22px 0;border-bottom:1px solid #ffffff2e;font:400 1.55rem var(--font-serif),Georgia,serif}.journey-hero li b{color:#efc8bd;font:700 .62rem var(--font-sans),sans-serif}.journey-paths{padding:clamp(70px,9vw,130px) max(20px,calc((100vw - 1380px)/2))}.journey-paths header{max-width:620px;margin-bottom:42px}.journey-paths h2,.journey-cta h2{margin:15px 0;font:400 clamp(2.9rem,5vw,5.2rem)/.98 var(--font-serif),Georgia,serif}.journey-paths>div{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #dfd0c5}.journey-paths article{min-height:330px;padding:32px;border-right:1px solid #dfd0c5}.journey-paths article:last-child{border:0}.journey-paths article small{color:#ae4d52;font-weight:700}.journey-paths h3{font:400 1.8rem/1.05 var(--font-serif),Georgia,serif}.journey-paths p{color:#7a685e;font-size:.88rem;line-height:1.65}.journey-paths article a{display:flex;justify-content:space-between;margin-top:28px;color:#9c4247;font-size:.76rem;font-weight:700;text-decoration:none}.journey-cta{padding:90px 20px;text-align:center;background:#e9d7c9}.journey-cta a{display:inline-flex;margin:20px 5px 0;padding:15px 22px;border:1px solid #aa4d52;border-radius:99px;color:#984147;font-size:.78rem;font-weight:700;text-decoration:none}.journey-cta a:first-of-type{background:#aa4d52;color:white}@media(max-width:850px){.journey-hero{grid-template-columns:1fr}.journey-hero aside{padding-block:50px}.journey-paths>div{grid-template-columns:1fr 1fr}.journey-paths article:nth-child(2){border-right:0}.journey-paths article:nth-child(-n+2){border-bottom:1px solid #dfd0c5}}@media(max-width:520px){.journey-hero>div{padding:64px 20px}.journey-hero h1{font-size:3.8rem}.journey-paths>div{grid-template-columns:1fr}.journey-paths article{min-height:auto;border-right:0;border-bottom:1px solid #dfd0c5!important}.journey-cta h2{font-size:2.8rem}}`}</style></>;
}
