import Link from 'next/link';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const services = [['Custom gifts','Personalised art and handcrafted objects made around a recipient, story or occasion.'],['Corporate gifting','Thoughtful gift sets for clients, teams, celebrations, launches and festive programmes.'],['Commercial artwork','Digital or hand-painted concepts for offices, hospitality, retail and branded spaces.'],['Event & wedding orders','Coordinated gifts, keepsakes and artistic details designed for your celebration.']];
export const metadata = { title: "Custom & Corporate Projects | Artzy's Studio", description: 'Custom art, corporate gifts, event orders and commercial creative work by Artzy’s Studio.' };

export default function CustomCorporatePage(){return <><Header/><main className="corporate-page">
  <section className="corporate-hero"><div><span className="service-eyebrow">Custom · corporate · commercial</span><h1>Your brief.<br/><em>Our artistic thinking.</em></h1><p>From one deeply personal gift to a coordinated corporate collection, Artzy&apos;s Studio develops original work around your purpose, quantity, budget and timeline.</p><div className="service-actions"><Link className="service-primary" href="/contact/?subject=custom-project">Start a project enquiry</Link><a className="service-secondary" href="https://wa.me/919158680722" target="_blank" rel="noreferrer">Discuss on WhatsApp</a></div></div><aside><span>For individuals</span><strong>Personal commissions &amp; occasion gifts</strong><span>For organisations</span><strong>Team, client &amp; festive gifting</strong><span>For spaces</span><strong>Custom artwork &amp; creative installations</strong></aside></section>
  <section className="corporate-services"><div className="digital-section-heading"><span className="service-eyebrow">Ways to work with us</span><h2>One studio, shaped around your requirement.</h2></div><div>{services.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="corporate-brief"><div><span className="service-eyebrow">A useful first brief</span><h2>Tell us these five things.</h2></div><ol><li>What you want to create</li><li>Who it is for</li><li>Quantity or artwork size</li><li>Budget range</li><li>Required delivery date</li></ol></section>
  <section className="corporate-process"><span className="service-eyebrow">How projects move</span><h2>Clear decisions at every stage.</h2><div><article><b>01</b><strong>Brief</strong><p>We understand the purpose, audience, quantity and practical requirements.</p></article><article><b>02</b><strong>Proposal</strong><p>The studio recommends a creative direction, estimate and expected timeline.</p></article><article><b>03</b><strong>Approval</strong><p>You review the concept, personalisation and production details.</p></article><article><b>04</b><strong>Create &amp; deliver</strong><p>Work begins after approval, with delivery planned for the confirmed date.</p></article></div><Link className="service-primary" href="/contact/?subject=custom-project">Send your project brief</Link></section>
  </main><Footer/></>}
